config/routes.rb
TypingFrenzy::Application.routes.draw do

  get 'static_pages/root'
  root to: 'static_pages#root'

  resource :session, only: [:create, :destroy, :new]
  resources :users, only: [:create, :new]

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  after_initialize :ensure_session_token

  validates :password_digest, presence: true
  # If a password was set, we validate it meets the requirements.
  # Note the `allow_nil`.
  validates(
    :password,
    length: { minimum: 1, allow_nil: true }
  )
  validates :session_token, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)

    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end


  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # Expose current_user method to the views
  helper_method :current_user
  helper_method :text
  helper_method :logged_in?

  private

  require 'csv'

  def read_csv
    csv_data = CSV.read 'test_words.csv'
    csv_data.to_a.flatten
  end


  def require_no_user!
    # redirect_to ??? unless current_user.nil?
  end

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def text
    @text_array = read_csv()
  end

  def logged_in?
    !current_user.nil?
  end

  def login_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_user!
    redirect_to new_session_url if current_user.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_no_user!, only: [:create, :new]

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user.nil?
      flash.now[:errors] = ["Incorrect username and/or password"]
      render :new
    else
      login_user!(user)
      redirect_to static_pages/root
    end
  end

  def destroy
    logout_user!
    redirect_to root_url
  end

  def new
    render :new
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_no_user!

  def create
    @user = User.new(user_params)
    if @user.save
      login_user!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def new
    @user = User.new
    render :new
  end

  private
  def user_params
    params.require(:user).permit(:password, :username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Make your life easier,
  # define the CSRF auth token in a helper
  # and put it in all the forms!
  def auth_token_input
    "<input
        type=\"hidden\"
        name=\"authenticity_token\"
        value=\"#{ form_authenticity_token }\">".html_safe
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<div class='navbar-div'>
  <nav class="navbar navbar-default my-navbar">
    <div class="container-fluid">

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li> <a id="countdown">[time] </a> </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Word Group <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a name='Home_Row_00' id='0' href="#">00-Home Row</a></li>
              <li><a name='In_Position_01' id='1' href="#">01-In Position</a></li>
              <li><a name='Out_Of_Position_02' id='2' href="#">02-Out of Position</a></li>
              <li><a name='Stretchers_03' id='3' href="#">03-Small Stretches</a></li>
              <li class="divider"></li>
              <li><a name='Punctuation_04' id='4' href="#">04-Punctuation</a></li>
              <li><a name='Numbers_05' id='5' href="#">05-Numbers</a></li>
              <li><a name='Top_Punctuation_055' id='5.5' href="#">05.5-Top Punctuation</a></li>
              <li class="divider"></li>
              <li><a name='HTML_06' id='6' href="#">06-HTML</a></li>
              <li><a name='CSS_07' id='7' href="#">07-CSS</a></li>
              <li><a name='JavaScript_08' id='8' href="#">08-JavaScript</a></li>
              <li><a name='Ruby_09' id='9' href="#">09-Ruby</a></li>
              <li><a name='Rails_10' id='10' href="#">10-Rails</a></li>
            </ul>
          </li> <!--dropdown -->

          <% if current_user.nil? %>
            <!-- <li><a class='my-sign-in' href="#">Sign In</a></li>
            <li><a class='my-sign-up' href="#">Sign Up</a></li> -->
          <% else %>
            <li><%= current_user.username %></li>
            <li><%= button_to "Logout", session_url, method: :delete %></li>
          <% end %>
        </ul>

      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</div> <!-- navbar-div -->

app/views/layouts/_new_session.html.erb
<div class='user-session-box new-session-box dialog-box' id='new-session-box'>
  <p class="my-dialog-font" id="">Sign In</p>

  <form action="<%= session_url %>" method="post">
    <%= render partial: "layouts/user_pass" %>
  </form>
</div>

app/views/layouts/_new_user.html.erb
<%= render "shared/errors" %>

<div class='user-session-box new-user-box dialog-box' id='new-user-box'>
  <p class="my-dialog-font" id="">Sign Up</p>

  <form action="<%= users_url %>" method="post">
    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>"
      >
    <%= render partial: "layouts/user_pass" %>
  </form>
</div>

app/views/layouts/_result_table.html.erb
<div class="CSSTableGenerator" >
  <table >
      <tr>
          <td class='result-label-1'>
            wpm:
          </td>

          <td class='result-string-1' id='result-string-1'>
            0
          </td>
      </tr>

      <tr>
          <td class='result-label-1'>
            accuracy (%):
          </td>

          <td class='result-string-2' id='result-string-2' >
              0
          </td>

      </tr>

  </table>
</div>

app/views/layouts/_user_pass.html.erb
<div class='my_username'>
  <label for="user_username">User Name </label>
  <input type="text"
         name="user[username]"
         id="user_username">
 </div>

<div class='my_password'>
  <label for="user_password">Password</label>
  <input type="password"
         name="user[password]"
         id="user_password" >
</div>
<br>
<input type="submit">

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Typing Frenzy</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <!-- Load all my .js files -->
    <%= javascript_include_tag "application" %>
    <!-- Load all my stylesheet files -->
    <%= stylesheet_link_tag "application", media: "all" %>
  </head>

  <body class='my-body'>

    <script>
      var test_array = '<%=raw text.as_json %>'
    </script>

    <%= yield %>
  </body>

</html>

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <ul>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %>

app/views/static_pages/root.html.erb
<div class='master'>
  <div class='canvas-div' row>
    <canvas class='my-canvas' id='my-canvas'></canvas>

    <div class='dialog-boxes-container'>

      <div class='start-game-box dialog-box' id='start-game'>

        <div class='game-over-dialog-box' id='game-over-dialog-box'>
          <p class='result-string-0'>
            Game Over
          </p>
          <%= render partial: "layouts/result_table" %>
        </div>

        <p class="my-dialog-font" id="">
          <button class='game-start-button myButton'
                  id='game-start-button'
                  type="button">
            Start Game
          </button>
        </p>
          <div class='instructions-box' id='instructions-box'>
            <p class='instructions-text'>
              Type the words on each fish!
            </p>
          </div>
      </div>
      <div class='keyboard-div' id='keyboard-div'>
        <canvas class='my-canvas-keyboard' id='my-canvas-keyboard'> </canvas>
        <span class='no-mistakes-msg' id='no-mistakes-msg'>no mistakes</span>
      </div>

      <%= render partial: "layouts/new_user" %>
      <%= render partial: "layouts/new_session" %>


    </div> <!-- dialog-boxes-container -->

    <%= render partial: "layouts/navbar" %>
  </div> <!-- canvas-div -->
</div> <!-- master -->

<!--########################################################################  -->

<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.2/underscore-min.js"></script>
<script type="application/javascript">
  (function () {
    this.wordList = '';
    var canvasEl = document.getElementById("my-canvas");
    canvasEl.width = TypingFrenzy.Game.DIM_X;
    canvasEl.height = TypingFrenzy.Game.DIM_Y;
    var ctx = canvasEl.getContext("2d");

    var keyboardCanvasEl = document.getElementById("my-canvas-keyboard");
    keyboardCanvasEl.width = 500
    keyboardCanvasEl.height = 176;
    var ctx_kbd = keyboardCanvasEl.getContext("2d");

    // Start or restart game.
    var startGame = function(demoMode) {
      // Remove previous game
      if (this.game !== 'undefined'){ this.game = null; };

      // Remove previous gameView
      if (this.currentGameView !== 'undefined'){ this.currentGameView = null; };

      this.game = new TypingFrenzy.Game({
        "ctx": ctx,
        "ctx_kbd": ctx_kbd,
        "demoMode": demoMode,  // Not used?
        'startWordList': this.wordList || 'In_Position_01'
        });
      this.currentGameView = new TypingFrenzy.GameView(this.game, ctx);
      this.currentGameView.start();
      if (demoMode){ this.currentGameView.unbindKeys();}  //comment this to debug the slowdown issue
    };

    startGame(true)

    // When an <li> is clicked, change the wordList to the corresponding list.
    var updateWordList = function() {
      this.game.getWordList(event.target.name);
      this.wordList = event.target.name;
    }
    $('.dropdown-menu li').on("click", function() { updateWordList(); })

    // Show Sign In and Sign Up dialog boxes on click.
    $('.my-sign-up').on("click", function() {
      document.getElementById("new-user-box").style.display = "block";
      document.getElementById("new-session-box").style.display = "none";
      })

    $('.my-sign-in').on("click", function(){
       document.getElementById("new-session-box").style.display = "block";
       document.getElementById("new-user-box").style.display = "none";
       })
       document.getElementById("instructions-box").style.display = "block";
    // When you click the start button...
    that = this;
    $('.game-start-button').on("click", function(){
      document.getElementById("start-game").style.display = "none";
      window.currentGameView.stop();
      startGame(false);
       })

  })();
</script>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render "shared/errors" %>

<form action="<%= users_url %>" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="user_username">User Name</label>
  <input type="text"
         name="user[username]"
         id="user_username"
         value="<%= @user.username %>">
  <br>

  <label for="user_password">Password</label>
  <input type="password"
         name="user[password]"
         id="user_password"
         value="<%= @user.password %>">
  <br>

  <input type="submit">
</form>